name: Selenium OrangeHRM Demo

on:
  schedule:
    - cron: '0 8 * * *' # cada día a las 08:00 UTC (10:00 hora de Madrid)
  workflow_dispatch: {}

jobs:
  run-login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (Chromium & Chromedriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          chromium-browser --version
          which chromedriver
          chromedriver --version

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium OrangeHRM script
        env:
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
        run: python scripts/orangehrm_scraper.py

      - name: Upload employees.csv as artifact
        uses: actions/upload-artifact@v4
        with:
          name: employees-data
          path: output/employees.csv
